import type {Metadata} from "next";
import {Inter} from "next/font/google";
import 'rsuite/dist/rsuite-no-reset.min.css';
import "../globals.css";
import {Header} from "@/fsd/widgets/header";
import {QueryProvider} from "@/fsd/core/providers/QueryProvider";
import ProtectedRoute from "@/fsd/core/providers/ProtectedRoute";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next core",
};

export default function RootLayout(
  {
    children,

  }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
    <body className={`${inter.className} px-4 overflow-hidden`}>
    <ProtectedRoute>
      <QueryProvider>
        <Header/>
        <main>
          {children}
        </main>
      </QueryProvider>
    </ProtectedRoute>
    </body>
    </html>
  );
}
